msgcode	delay	message
HI	10	Welcome to Exercise 9
INTRO1	10	Today we are going to practice a safe take off by keeping outside of the so called dead mans curve, that is the region whereby an engine failure would not be recoverable by autorotation. Such regions are at low altitude and low airspeed
INTRO2	10	To safely takeoff we need to gather airspeed close to the ground and only climb once we reach 50 knots
INTRO3	10	Before we increase airspeed we need to come to a low hover and check for traffic left and right. Come to a hover
LAND	30	This exercise should be started when landing. I'll wait for you to land
GATHERAIRSPEED	10	Good keep gathering airspeed
TRANSLIFT	10	Watch out for transitional lift which may make us climb, so lower collective or push the cyclic forwards to keep low
FASTENOUGH	10	You've reached 50 knots so you can now start climbing. Well done
LETSGO	10	All clear, push the cyclic forwards to gather airspeed. Keep low
GOODHOVER	5	"Good hovering, groundspeed " .. math.floor(groundspeed) .. " vert " .. math.floor(ELEVATION) .. " alt " .. math.floor(y_agl)
OUTOFHOVER1	10	You've climbed out of the low hover, descend
OUTOFHOVER2	10	"You are drifting to much, try and stabilise the hover, ground speed " .. math.floor(groundspeed)
TOOHIGHSLOW	5	Too high with insufficient airspeed
GOODLEFTTURN	10	Take a good look left
GOODRIGHTTURN	10	Take a good look right
